### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by briantho** [th-ch/youtube-music#1791]
### Preflight Checklist

- [X] I use the latest version of YouTube Music (Application).
- [X] I have searched the [issue tracker](https://github.com/th-ch/youtube-music/issues) for a bug report that matches the one I want to file, without success.
- [X] I understand that **th-ch/youtube-music has NO affiliation with Google or YouTube**

### YouTube Music (Application) Version

3.3.2.0

### Checklists

- [X] I use the portable version of the YouTube Music Application.
- [ ] I can reproduce this issue in the [official YTM web version](https://music.youtube.com).

### What operating system are you using?

Windows

### Operating System Version

Windows 11 23H2

### What CPU architecture are you using?

x64

### Reproduction steps

1. Have the downloader plugin enabled. 
2. Play a song
3. Click the 3 vertical dots menu to bring up the context menu. 
4. Click the download button  

### Expected Behavior

I expect to be able to download a song. 

### Actual Behavior

Sometimes the downloader works, but about 75% of the time it fails with the message Argh! Apologies Download Failed... 
nct::ERR_FAILED
Seems to happen randomly. Sometimes i am able to download several songs no problem. Then, i hit this error, and i keep trying again and again till eventually it works

![image](https://github.com/th-ch/youtube-music/assets/3977205/50ec697b-ad66-401b-adf8-a09fc4002f53)

### Enabled plugins

Ad blocker
Downloader
In app menu
Navigation

### Additional Information

I would provide a log, but it is unclear to me how to do so...

**Comment by JellyBrick** [comment]
Are you using a proxy?

**Comment by briantho** [comment]
> Are you using a proxy?

No. I'm not using a proxy. I do have a dual wan load balancing edgerouter set up. I can try disabling one of the wan's but I'm not sure if that will help. Can you explain to me on how to do a debug log???

**Comment by ArjixWasTaken** [comment]
> > Are you using a proxy?
> 
> No. I'm not using a proxy. I do have a dual wan load balancing edgerouter set up. I can try disabling one of the wan's but I'm not sure if that will help. Can you explain to me on how to do a debug log???

As a general advice, when you want to see logs of GUI applications, you usually launch them from the command line.

In my case, I do:

```cmd
cd %USERPROFILE%\AppData\Local\Programs\youtube-music
".\YouTube Music.exe"
```

![image](https://github.com/th-ch/youtube-music/assets/53124886/be67390b-99df-4ddb-8d19-428cf50184d2)

You just locate where the executable of Youtube Music is, and launch it like I did

**Comment by ArjixWasTaken** [comment]
Step-by-step video:


https://github.com/th-ch/youtube-music/assets/53124886/ef94a4f2-a143-4aeb-90bb-41b4861f8b75

**Comment by briantho** [comment]
Ah ok. I thought there was something else you had to do. I didn't realize all I needed to do was run it from cli. I'm not able to test this right now, but should be able to in a few hours. I'll post the output once I get a chance

**Comment by briantho** [comment]
This is the error/output I get. Let me know what I should try
![image](https://github.com/th-ch/youtube-music/assets/3977205/83a6f58d-a75f-4dd7-b8db-577b00586f76)

**Comment by NotShige** [comment]
Same problem here too! When downloading my Liked Songs playlist, once it hits around 250 songs, the program crashes without any notice but shows up on the logs.

![cmd_rld7BntwvV](https://github.com/th-ch/youtube-music/assets/20384051/5f32c3ac-8106-4151-9eb5-8cda2b5ed416)

Trying to continue downloading the songs on where it stopped results in an error message like above at first, but then when I restart the program it works again. Very weird.

**Comment by JellyBrick** [comment]
> Same problem here too! When downloading my Liked Songs playlist, once it hits around 250 songs, the program crashes without any notice but shows up on the logs.
> 
> ![cmd_rld7BntwvV](https://private-user-images.githubusercontent.com/20384051/307627490-5f32c3ac-8106-4151-9eb5-8cda2b5ed416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzgwNjgsIm5iZiI6MTcwODkzNzc2OCwicGF0aCI6Ii8yMDM4NDA1MS8zMDc2Mjc0OTAtNWYzMmMzYWMtODEwNi00MTUxLTllYjUtOGNkYTJiNWVkNDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA4NTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMWQxMGFmMWYzOTgyNDJkOTMzMjgyOTc4NmU2MjY4MGQwZTY5ODlhNTg4ZmVkNjQ0OGVjN2ZiMWQxYTRlZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1bsUhGKaxVjpJlTar6oiCQ7KWhAnRmRGu14Auz3qEtc)
> 
> Trying to continue downloading the songs on where it stopped results in an error message like above at first, but then when I restart the program it works again. Very weird.

This issue was fixed at https://github.com/th-ch/youtube-music/commit/fd6ba1eda113e703792c0ffef4f27c8e48e137a7

**Comment by NotShige** [comment]
@JellyBrick Slightly different error this time after compiling from source, happens on both .mp3 and Source preset.
![image](https://github.com/th-ch/youtube-music/assets/20384051/7b14a6d9-ff69-44e3-978e-16831475f16f)
![image](https://github.com/th-ch/youtube-music/assets/20384051/1b58bd73-a55f-49d1-ab76-1df9ae85c683)

Also noticed that this message shows up when I select the .mp3 preset.

![cmd_Kui5b0OjUj](https://github.com/th-ch/youtube-music/assets/20384051/178c5895-b3ef-4f10-ac74-852124181d29)

**Comment by JellyBrick** [comment]
@NotShige Are you using a 32-bit version of Windows?

**Comment by JellyBrick** [comment]
@NotShige Are you experiencing the same issue in 55c934a?

**Comment by briantho** [comment]
OK, so I decided to try and disable wan2 of my dual wan setup. The Problem immediately went away. I was able to download 20 songs in my liked music, with 0 problems. I reenabled wan2, ran the same test, and sure enough about 6 songs into downloading the error came back...  @JellyBrick is there any way to get this working with a dual wan setup? I know dual wan is not a common thing in most homes, but I would greatly appreciate it if you could figure it out

**Comment by CheeseFort** [comment]
I am experiencing the same issue as @briantho. I am not using dual wan. My internet is Carrier-grade NAT with t-mobile home internet.
![image](https://github.com/th-ch/youtube-music/assets/110061484/c8c42974-233d-4488-901c-fba046ad6983)

**Comment by briantho** [comment]
> I am experiencing the same issue as @briantho. I am not using dual wan. My internet is Carrier-grade NAT with t-mobile home internet. ![image](https://private-user-images.githubusercontent.com/110061484/311473686-c8c42974-233d-4488-901c-fba046ad6983.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjEwNzksIm5iZiI6MTcxMDEyMDc3OSwicGF0aCI6Ii8xMTAwNjE0ODQvMzExNDczNjg2LWM4YzQyOTc0LTIzM2QtNDQ4OC05MDFjLWZiYTA0NmFkNjk4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwMTMyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTFmNDY1ZTA3MGMyNTAxMGMzOGMzNjZlNTcxNmJiNDc5N2M3YTdkMWExNDMyYTQ1YjE0YzAyOTY2ZTM1NTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g_iBE6vNWVLojUeDNojF-ZJyxgg5uJt6Du4shBJkPR0)

ah, very interesting. I forgot to mention, the wan2 on my router is using starlink, which is in turn using cgnat. now it all makes sense, since I'm using load balancing some packets go through my local isp cable provider, and some go through starlink. In my test, i tried disabling wan2, aka starlink. I'll try disabling wan1, aka my local ISP cable provider tomorrow, and see if downloading works though starlink only. If that's the case, then it's not a dual wan issue, but a issue with CGnat. I'll test tomorrow and report back.

**Comment by Temtaime** [comment]
Same problem :/

**Comment by rahulsah18** [comment]
did anyone get the exact solution
![Screenshot 2024-06-13 083940](https://github.com/th-ch/youtube-music/assets/172564117/a78c60a3-51ca-4a13-86cf-dc6b6d582ca5)

**Comment by seanhalim** [comment]
Youtube music 1.2 used to be my work around, but now I'm getting this same error on any versions on any of my laptops this is really vexing TwT

**Comment by dejl** [comment]
I get same issue. It's not just playlists, some songs just ERR when downloading through this program
yt-dlp can grab it fine though

**Comment by franz-dc** [comment]
@JellyBrick is there any drawback of not using net fetch for the downloader plugin?

**Comment by Iorweth333** [comment]
I hoped for something that would be able to download entire playlist for later use in offline but, while downloading songs one by one works fine, downloading playlist fails with a number of error popup windows like below:

![Image](https://github.com/user-attachments/assets/8e180a1c-ddcd-4791-879e-a870b134e6f1)

Trying to start the download of the playlist again I got "Folder already exists" error - but nothing new showed up in my Downloads folder...
What's wrong? Hot to fix it?

**Comment by Rednas83** [comment]
Just tried it today and I also experience issues on windows 11
* Music is downloaded in the download folder instead of the specified folder
* Single songs are downloaded but sometimes need multiple attempts to actualy download. Perhaps add a log for failed downloads in the download folder?
* Multiple songs like albums are not downloaded at all

Perhaps an idea to add support for synchronizing the full library automaticly with the downloads folder?

**Info**
![Image](https://github.com/user-attachments/assets/1d00614e-2ed3-40fe-b583-08328670a431)
![Image](https://github.com/user-attachments/assets/67eaddef-7908-4a82-90d1-f8de819deb31)

**Comment by JellyBrick** [comment]
> [@JellyBrick](https://github.com/JellyBrick?rgh-link-date=2025-02-22T10%3A47%3A14.000Z) is there any drawback of not using net fetch for the downloader plugin?

![Image](https://github.com/user-attachments/assets/048bfa04-7a4a-4134-942e-eb86f192ccd7)

It supports the automatic management of system proxy configuration

**Comment by AsuToki360** [comment]
Having the same issue, sometimes when downloading I get ERR_FAILED, sometimes it works, it's kinda janky right now.

CachyOS (Arch Linux based), Gnome 48, installed via Cachy's official repository `(cachyos/youtube-music 3.10.0-1 [installed])`

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/cc8482fe-9468-4042-ae7a-4bdebb73f8c4" />
